### Import pandas

In [80]:
import pandas as pd

In [81]:
df = pd.read_csv('hotel_bookings.csv')
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

### UNDERSTAND THE DATASET

### number of rows and columns

In [82]:
df.shape

(119390, 32)

### column names

In [83]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

### first 5 records

In [84]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

### last 5 records

In [85]:
df.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

### data types

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

### statistical information

In [87]:
df.describe(include="all")

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
count,119390,119390.000000,119390.000000,119390.000000,119390,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,...,119390,103050.000000,6797.000000,119390.000000,119390,119390.000000,119390.000000,119390.000000,119390,119390
unique,2,NaN,NaN,NaN,12,NaN,NaN,NaN,NaN,NaN,...,3,NaN,NaN,NaN,4,NaN,NaN,NaN,3,926
top,City Hotel,NaN,NaN,NaN,August,NaN,NaN,NaN,NaN,NaN,...,No Deposit,NaN,NaN,NaN,Transient,NaN,NaN,NaN,Check-Out,2015-10-21
freq,79330,NaN,NaN,NaN,13877,NaN,NaN,NaN,NaN,NaN,...,104641,NaN,NaN,NaN,89613,NaN,NaN,NaN,75166,1461
mean,NaN,0.370416,104.011416,2016.156554,NaN,27.165173,15.798241,0.927599,2.500302,1.856403,...,NaN,86.693382,189.266735,2.321149,NaN,101.831122,0.062518,0.571363,NaN,NaN
std,NaN,0.482918,106.863097,0.707476,NaN,13.605138,8.780829,0.998613,1.908286,0.579261,...,NaN,110.774548,131.655015,17.594721,NaN,50.535790,0.245291,0.792798,NaN,NaN
min,NaN,0.000000,0.000000,2015.000000,NaN,1.000000,1.000000,0.000000,0.000000,0.000000,...,NaN,1.000000,6.000000,0.000000,NaN,-6.380000,0.000000,0.000000,NaN,NaN
25%,NaN,0.000000,18.000000,2016.000000,NaN,16.000000,8.000000,0.000000,1.000000,2.000000,...,NaN,9.000000,62.000000,0.000000,NaN,69.290000,0.000000,0.000000,NaN,NaN
50%,NaN,0.000000,69.000000,2016.000000,NaN,28.000000,16.000000,1.000000,2.000000,2.000000,...,NaN,14.000000,179.000000,0.000000,NaN,94.575000,0.000000,0.000000,NaN,NaN
75%,NaN,1.000000,160.000000,2017.000000,NaN,38.000000,23.000000,2.000000,3.000000,2.000000,...,NaN,229.000000,270.000000,0.000000,NaN,126.000000,0.000000,1.000000,NaN,NaN
max,NaN,1.000000,737.000000,2017.000000,NaN,53.000000,31.000000,19.000000,50.000000,55.000000,...,NaN,535.000000,543.000000,391.000000,NaN,5400.000000,8.000000,5.000000,NaN,NaN

### check missing values

In [88]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

### handle missing values

In [89]:
df['children']=df['children'].fillna(0)

df['country']=df['country'].fillna('Unknown')

df['agent']=df['agent'].fillna(0)

df['company']=df['company'].fillna(0)

In [90]:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

### Remove duplicates

In [91]:
df.duplicated().sum()

np.int64(31994)

In [92]:
df=df.drop_duplicates()

In [93]:
df.duplicated().sum()

np.int64(0)

### Correct data types

In [94]:
numeric_columns = [
    "adults",
    "children",
    "babies",
    "is_canceled",
    "lead_time",
    "stays_in_weekend_nights",
    "stays_in_week_nights",
    "adr"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

### Remove unnecessary columns

In [95]:
df = df.drop(columns=["agent","company"], errors="ignore")

### Total_Guests

In [96]:
df["Total_Guests"] = (
    df["adults"] +
    df["children"] +
    df["babies"]
)

In [97]:
df[["adults", "children", "babies", "Total_Guests"]].head()

   adults  children  babies  Total_Guests
0       2       0.0       0           2.0
1       2       0.0       0           2.0
2       1       0.0       0           1.0
3       1       0.0       0           1.0
4       2       0.0       0           2.0

### Stay_Nights

In [98]:
df["Stay_Nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
)

In [99]:
df[
    [
        "stays_in_weekend_nights",
        "stays_in_week_nights",
        "Stay_Nights"
    ]
].head()

   stays_in_weekend_nights  stays_in_week_nights  Stay_Nights
0                        0                     0            0
1                        0                     0            0
2                        0                     1            1
3                        0                     1            1
4                        0                     2            2

### Booking_Status

is_canceled = 1 → Cancelled
is_canceled = 0 → Completed

In [100]:
df["Booking_Status"] = df["is_canceled"].map({
    1: "Cancelled",
    0: "Completed"
})

In [101]:
df[["is_canceled", "Booking_Status"]].head()

   is_canceled Booking_Status
0            0      Completed
1            0      Completed
2            0      Completed
3            0      Completed
4            0      Completed

### Check invalid values

In [102]:
df[df["Total_Guests"] <= 0].shape

(166, 33)

In [103]:
df[df["Stay_Nights"] < 0].shape

(0, 33)

In [104]:
df[df["adr"] < 0].shape

(1, 33)

In [105]:
df = df[df["Total_Guests"] > 0]

### Basic Analysis

total bookings

In [106]:
total_bookings = len(df)

print("Total Bookings:", total_bookings)

Total Bookings: 87230

total cancelled bookings

In [107]:
total_cancelled = df["is_canceled"].sum()

print("Total Cancelled Bookings:", total_cancelled)

Total Cancelled Bookings: 24009

cancellation rate

In [108]:
cancellation_rate = (
    df["is_canceled"].mean() * 100
)

print("Cancellation Rate:", round(cancellation_rate, 2), "%")

Cancellation Rate: 27.52 %

Average Daily Rate

In [109]:
average_adr = df["adr"].mean()

print("Average ADR:", round(average_adr, 2))

Average ADR: 106.52

Average Stay Duration

In [110]:
average_stay = df["Stay_Nights"].mean()

print("Average Stay Duration:", round(average_stay, 2))

Average Stay Duration: 3.63

City hotel Bookings

In [111]:
city_bookings = (df["hotel"] == "City Hotel").sum()

print("City Hotel Bookings:", city_bookings)

City Hotel Bookings: 53274

Resort Hotel Bookings

In [112]:
resort_bookings = (df["hotel"] == "Resort Hotel").sum()

print("Resort Hotel Bookings:", resort_bookings)

Resort Hotel Bookings: 33956

### Export cleaned dataset

cleaned_hotel_bookings.csv

In [113]:
df.to_csv(
    "cleaned_hotel_bookings.csv",
    index=False
)

In [114]:
pd.read_csv("cleaned_hotel_bookings.csv").head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,Total_Guests,Stay_Nights,Booking_Status
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,Transient,0.0,0,0,Check-Out,2015-07-01,2.0,0,Completed
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,Transient,0.0,0,0,Check-Out,2015-07-01,2.0,0,Completed
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,Transient,75.0,0,0,Check-Out,2015-07-02,1.0,1,Completed
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,Transient,75.0,0,0,Check-Out,2015-07-02,1.0,1,Completed
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,Transient,98.0,0,1,Check-Out,2015-07-03,2.0,2,Completed

### Basic analysis

In [115]:
total_bookings = len(df)
total_cancelled = df['is_canceled'].sum()
cancellation_rate = (total_cancelled / total_bookings * 100)
avg_adr = df['adr'].mean()
df['Stay_Nights'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']
avg_stay = df['Stay_Nights'].mean()
city_hotel_bookings = df[df['hotel'] == 'City Hotel'].shape[0]
resort_hotel_bookings = df[df['hotel'] == 'Resort Hotel'].shape[0]

print(f"1. Total bookings: {total_bookings}")
print(f"2. Total cancelled: {total_cancelled}")
print(f"3. Cancellation rate: {cancellation_rate:.2f}%")
print(f"4. Average Daily Rate: {avg_adr:.2f}")
print(f"5. Average stay duration: {avg_stay:.2f}")
print(f"6. City Hotel bookings: {city_hotel_bookings}")
print(f"7. Resort Hotel bookings: {resort_hotel_bookings}")

1. Total bookings: 87230
2. Total cancelled: 24009
3. Cancellation rate: 27.52%
4. Average Daily Rate: 106.52
5. Average stay duration: 3.63
6. City Hotel bookings: 53274
7. Resort Hotel bookings: 33956

In [116]:
df.to_csv("cleaned_hotel_bookings.csv", index=False)

In [117]:
import pandas as pd

# 1. Original file read pannrom
df = pd.read_csv("hotel_bookings.csv") # ungal original file name ithu thaan na?

# 2. Cleaning
# Missing values drop or fill
df = df.dropna(subset=['children', 'country']) # Example cleaning
df['children'] = df['children'].fillna(0)

# Duplicates remove
df = df.drop_duplicates()

# 3. New column
df['Stay_Nights'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']

# 4. Save - MAIN STEP
df.to_csv("cleaned_hotel_bookings.csv", index=False)

print(f"✅ SUCCESS! {len(df)} rows saved to cleaned_hotel_bookings.csv")
print(df.head(3))

✅ SUCCESS! 86940 rows saved to cleaned_hotel_bookings.csv
          hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July
1  Resort Hotel            0        737               2015               July
2  Resort Hotel            0          7               2015               July

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1
1                        27                          1
2                        27                          1

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  agent  company  \
0                        0                     0       2  ...    NaN      NaN
1                        0                     0       2  ...    NaN      NaN
2                        0                     1       1  ...    NaN      NaN

  days_in_waiting_list customer_type   adr required_car_parking_spaces  \
0                    0     Transient   0.0                           0
1                    0     Transient   0.0                           0
2                    0     Transient  75.0                           0

   total_of_special_requests  reservation_status  reservation_status_date  \
0                          0           Check-Out               2015-07-01
1                          0           Check-Out               2015-07-01
2                          0           Check-Out               2015-07-02

  Stay_Nights
0           0
1           0
2           1

[3 rows x 33 columns]